# Site settings 配置站点
title: "Dan's Blog"
description: 'Dan Larimer is the '
keyword: 'EOS, Blockchain, Block.One'
url: 'http://davidmaliglowka.com' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: /dansblog

# Navigation links
nav:
  home: '/dansblog/'
  tags: '/dansblog/tags.html'

# Footer
footer:
  since: 2018

# Author
author: 'Dan Larimer'
nickname: 'Dan'
bio: '<i>CTO, Block.one</i> </br style="line-height: 22px"> Building crypto-economic solutions for securing life, liberty, property, and justice for all.'
avatar: '/assets/img/dan-profile.jpg'

# Search
search: true

# Night mode
nightMode: true

# Comments
comments:
  disqus: true
  disqus_url: 'https://maliglow.disqus.com/embed.js'

# MathJax
mathjax: false

# Share
social-share: true
social-share-items: ['linkedin', 'facebook', 'twitter']

# theme color
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'glamorous'

# SNS settings
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: '//github.com/bytemaster'
  twitter: '//twitter.com/bytemaster7'
  medium: '//medium.com/@bytemaster'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 5
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
